### PR TITLE
fix perl shebang

### LINKED ISSUE #766: mysqltuner.pl: env: bad interpreter: No such file or directory
Hello,

The new version does not work on CentOS 6,7,8 and fails with the error:

```
mysqltuner.pl: env: bad interpreter: No such file or directory
```

see it has no path for `env`:

```
#!env perl
# mysqltuner.pl - Version 2.5.3
# High Performance MySQL Tuning Script
```

should be 

```
#!/bin/env perl
# mysqltuner.pl - Version 2.5.3
# High Performance MySQL Tuning Script
```

### PR DESCRIPTION
**Pull request by FabioPedretti**
Current shebang gives this error:
$ ./mysqltuner.pl
-bash: ./mysqltuner.pl: cannot execute: required file not found

Also fixes #766.

### CODE REVIEW

File: mysqltuner.pl [hunk 1]
```diff
@@ -1,4 +1,4 @@
-#!env perl
+#!/usr/bin/perl
```
Comment (chenrui333) [inline mysqltuner.pl:1]: This would be a bit better
```suggestion
#!/usr/bin/env perl
```

Comment (chenrui333) [reply mysqltuner.pl:1]: relates to https://github.com/major/MySQLTuner-perl/pull/762
